### ISSUE TITLE
Support for Generic NotNull

### ISSUE THREAD

**Issue by Sam-Kruglov** [leangen/graphql-spqr-samples#13]
Read all the not null annotations (javax, idea, lombok etc) and treat them like `GraphQLNonNull`. Also propagate these nonnulls from types to input types

**Comment by kaqqao** [comment]
1) All common non-null annotations are already supported everywhere.

2) This is a project with samples only. Please open library issues on the library project.

**Comment by Sam-Kruglov** [comment]
Sorry, didn't realize it is a sample repo. For me didn't work, I'll try more and file a more detailed issue in case of failure
